### ISSUE TITLE
Throttle middleware affects the entire application scan

### ISSUE THREAD

**Issue by MuriloChianfa** [vormkracht10/laravel-seo-scanner#19]
hello friend, my project have a lower throttle middleware to some routes, and this impact on the scam.
have any ideia to bypass the throttle middleware?
its possible to ignore this?

**Comment by Baspa** [comment]
Only one request is made for each url, so it should only be visited once by the scan. Can you tell me how many requests can be made each minute to your routes and how many requests you receive within that minute?

**Comment by MuriloChianfa** [comment]
apparently the throttle middleware groups some routes when used with the Route::group function, thus forcing the route group.
I defined the access limit as 30:1 (30 requests every 1 minute) but I have about 40 routes protected by the same throttle middleware to avoid flooding, do you think that is too low?

**Comment by Baspa** [comment]
Hmm I don't think that's too low at all. But I think because it's grouped we reach the limit too fast. I'm currently thinking about building some throttle mechanism into the package so you can configure the maximum amount of requests done per minute. You're probably not the only one using the throttle middleware so we should find a solution for this. 

I will try to find a good solution for this, if you have any ideas in the meantime please let me know 👍🏼

**Comment by Baspa** [comment]
I think the problem is with the `isBrokenLink` method which makes a request with `curl` to determine if the link is broken: 

```php
if (! function_exists('isBrokenLink')) {
    function isBrokenLink(string $url): bool
    {
        $statusCode = (string) getRemoteStatus($url);

        if (str_starts_with($statusCode, '4') || str_starts_with($statusCode, '5') || $statusCode === '0') {
            return true;
        }

        return false;
    }
}

if (! function_exists('getRemoteStatus')) {
    function getRemoteStatus(string $url): int
    {
        return cache()->driver(config('seo.cache.driver'))->tags('seo')->rememberForever($url, function () use ($url) {
            $ch = curl_init($url);

            $options = [
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_HEADER => true,
                CURLOPT_NOBODY => true,
                CURLOPT_TIMEOUT => 10,
                CURLOPT_FOLLOWLOCATION,
            ];

            if (app()->runningUnitTests()) {
                $options[CURLOPT_SSL_VERIFYHOST] = false;
                $options[CURLOPT_SSL_VERIFYPEER] = false;
                $options[CURLOPT_SSL_VERIFYSTATUS] = false;
            }

            curl_setopt_array($ch, $options);
            curl_exec($ch);

            $statusCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);

            curl_close($ch);

            return $statusCode;
        });
    }
}
```

## Possible solutions
- We could use [Guzzle Advanced Throttle](https://github.com/hamburgscleanest/guzzle-advanced-throttle). I don't know if using Guzzle slows down making the requests, I should check that first. 
- Use some sort of queue mechanism in the package which can limit the number of requests made at any given time.

**Comment by Baspa** [comment]
I'm a little bit late but I got a solution @MuriloChianfa
