### ISSUE TITLE
getimagesize(): Error on Meta Pixel Code

### ISSUE THREAD

**Issue by jloguercio** [vormkracht10/laravel-seo-scanner#70]
![Captura](https://github.com/user-attachments/assets/50fcf58a-aab3-4636-8021-8641e43e3941)

Get this error on everyscan.

**Comment by Baspa** [comment]
Can you show me the whole error please? @jloguercio

**Comment by jloguercio** [comment]
![Captura](https://github.com/user-attachments/assets/98ddc1c4-1f92-4ab4-8718-1aaa37d54e90)


> Can you show me the whole error please? @jloguercio

**Comment by Baspa** [comment]
@markvaneijk any idea why this might happen with the Facebook Pixel?

**Comment by markvaneijk** [comment]
Yeah, that pixel does not have a size probably or they block accessing the file by 'bots'.

Fix should be adding try/catch, because there can be more cases a file can't be accessed.

In case of an error we should just skip the file and ignore it. We have other checks like BrokenImageCheck to cover for that.

**Comment by Baspa** [comment]
@jloguercio fixed in v3.12.5 please let me know if any errors still occur
